flake8 linting
mundialis/actinia_core pull request #146
Opened 2021-02-19 11:38 UTC by anikaweinmann

2     E222 multiple spaces after operator

2021-02-25 08:57 UTC, mmacata commented
Is this still a Draft? Or can I review? @anikaweinmann

2021-02-25 09:27 UTC, anikaweinmann commented
@mmacata you can review

2021-03-08 17:09 UTC, neteler approved these changes
Nice work!

2021-03-09 13:03 UTC, mmacata requested changes
Great! Thank you for this huge effort! This improves the quality a lot :) 
I have some remarks though but I'm happy to see this in action.

2021-03-09 13:03 UTC, mmacata commented on .flake8
> +    ./actinia_core/resources/common/app.py: E402, E501
I find it helpful to have a comment somewhere explaining the PEP8 codes. For actinia-module-plugin e.g. I added them on top: https://github.com/mundialis/actinia-module-plugin/blob/main/.flake8#L3

2021-03-09 13:27 UTC, anikaweinmann commented on src/actinia_core/testsuite.py
> +# from .endpoints import create_endpoints
Yes the tests are all running. I will remove the lines

2021-03-09 13:31 UTC, anikaweinmann commented on .flake8
> +# ./actinia_core/resources/common/list_grass_modules.py: F821: undefined names after missing import PyQt4 (not used file?)
The module XML is transfromed to a module list and I think it is written to the `grass_module_list.py`. I think it is only a script to create the file.

2021-03-09 15:31 UTC, anikaweinmann commented on src/actinia_core/main.py
> +# if os.environ.get('DEFAULT_CONFIG_PATH'):
Yes it is possible

2021-03-09 15:33 UTC, mmacata commented on src/actinia_core/main.py
> +# if os.environ.get('DEFAULT_CONFIG_PATH'):
cool

2021-03-09 15:48 UTC, mmacata approved these changes

2021-03-10 06:40 UTC, merged